const LOW_PRICE = 10000;
const HIGHT_PRICE = 50000;
const POPUP_PHOTO_WIDTH = 45;
const POPUP_PHOTO_HEIGHT = 40;
const FILES_TYPES = ['gif', 'jpg', 'jpeg', 'png'];
const RENDER_DELAY = 500;
const TOKYO_LAT = 35.652832;
const TOKYO_LNG = 139.839478;
const SIMILAR_OFFERS_COUNT = 10;

export {
  LOW_PRICE, HIGHT_PRICE, POPUP_PHOTO_WIDTH, POPUP_PHOTO_HEIGHT,
  FILES_TYPES, RENDER_DELAY, TOKYO_LAT, TOKYO_LNG,
  SIMILAR_OFFERS_COUNT
};
